### Site Settings ###
title               : Stefan Radlwimmer
description         : >-                               # >- means to ignore newlines until "url:"
  Hi, I am Stefan Radlwimmer, an Austrian Game Engineering Enthusiast working at <a href='https://developer.vuforia.com/home/'>Vuforia, a PTC Technology</a>.<br/><br/>
  I currently work as Senior Augmented Developer responsible for <a href='https://www.ptc.com/en/products/vuforia/vuforia-expert-capture'>Vuforia Expert Capture</a> and 
  a proprietary AR Framework based on Unity Engine.

url                 : "https://stefan-radlwimmer.dev"  # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]

### Google Analytics ###
google_analytics    : UA-173126226-1

### Author Info ###
author:
  name              : Stefan Radlwimmer
  image             : assets/author.image.jpg
  email             : contact@stefan-radlwimmer.dev
# facebook          : your_username
  github            : StefanRadlwimmer
# gitlab            : your_username
# instagram         : your_username
  linkedin          : stefan-radlwimmer
# stackoverflow     : your_user_id
# twitch            : your_username
# twitter           : your_username
# youtube           : your_channel_name

### Collections ###
collections:
  projects:
    output: false
    permalink: /projects/:name
  portfolio:
    output: true
    permalink: /portfolio/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# Posts default Permalink
permalink: articles/:title

plugins:
  - jemoji

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  
theme: jekyll-theme-slate